"""Right-side-coverage S-cruise geometry for the DEMO_PARKING map.

This module is the single source of truth for the demo inspection route. Both
the fresh-database seed and the existing-dev-database sync MUST call the same
builder so the two can never drift.

The robot only detects the side to its right. Every inspection pose therefore
places the parking slot in the robot's local right half-plane:

    dot(slot_center - robot_pose, vehicle_right_vector(theta)) > 0

with vehicle_right_vector(theta) = (sin(theta), -cos(theta)).

Body frame (ROS convention):

    local +X = forward
    local +Y = left
    local -Y = right

Slot codes are generated by seed.py as:

    A-01..A-09  top group 1 (x = 2.5 + col*2.15, y = 31.5)
    A-10..A-18  top group 2 (x = 27.0 + col*2.15, y = 31.5)
    A-19..A-27  column 1   (x = 5.0,  y = 3.0 + row*2.8)
    A-28..A-36  column 2   (x = 17.0, y = 3.0 + row*2.8)
    A-37..A-45  column 3   (x = 29.0, y = 3.0 + row*2.8)
    A-46..A-54  column 4   (x = 43.0, y = 3.0 + row*2.8)
"""

from __future__ import annotations

import math
from typing import NamedTuple

REMOTE_WAITING = {"x": 1.2, "y": 1.2, "theta": math.pi / 2}

_TOP_LANE_OFFSET_Y = -2.8
_COLUMN_LANE_OFFSET = 3.0


class SlotRef(NamedTuple):
    code: str
    x: float
    y: float


def slot_number(code: str) -> int:
    return int(code.rsplit("-", 1)[-1].lstrip("0") or "0")


def group_of(code: str) -> str:
    n = slot_number(code)
    if n <= 18:
        return "top"
    if n <= 27:
        return "col1"
    if n <= 36:
        return "col2"
    if n <= 45:
        return "col3"
    return "col4"


def vehicle_right_vector(theta: float) -> tuple[float, float]:
    return (math.sin(theta), -math.cos(theta))


def slot_is_on_vehicle_right(robot: dict, slot: dict) -> bool:
    rel = (slot["x"] - robot["x"], slot["y"] - robot["y"])
    right = vehicle_right_vector(robot["theta"])
    return rel[0] * right[0] + rel[1] * right[1] > 0


def inspection_pose(slot: SlotRef) -> dict:
    """Return the robot pose from which the slot is on the robot's right side."""
    group = group_of(slot.code)
    if group == "top":
        return {"x": slot.x, "y": slot.y + _TOP_LANE_OFFSET_Y, "theta": math.pi}
    if group in {"col1", "col3"}:
        return {"x": slot.x + _COLUMN_LANE_OFFSET, "y": slot.y, "theta": -math.pi / 2}
    return {"x": slot.x - _COLUMN_LANE_OFFSET, "y": slot.y, "theta": math.pi / 2}


def ordered_groups(slots: list[SlotRef]) -> list[list[SlotRef]]:
    """S-cruise order: col1 down, col2 up, col3 down, col4 up, top west."""
    col1 = sorted((s for s in slots if group_of(s.code) == "col1"), key=lambda s: -s.y)
    col2 = sorted((s for s in slots if group_of(s.code) == "col2"), key=lambda s: s.y)
    col3 = sorted((s for s in slots if group_of(s.code) == "col3"), key=lambda s: -s.y)
    col4 = sorted((s for s in slots if group_of(s.code) == "col4"), key=lambda s: s.y)
    top = sorted((s for s in slots if group_of(s.code) == "top"), key=lambda s: -s.x)
    return [col1, col2, col3, col4, top]


def ordered_codes(slots: list[SlotRef]) -> list[str]:
    return [slot.code for group in ordered_groups(slots) for slot in group]


def _dedupe(points: list[dict]) -> list[dict]:
    out: list[dict] = []
    for point in points:
        if not out or out[-1]["x"] != point["x"] or out[-1]["y"] != point["y"]:
            out.append({"x": round(point["x"], 4), "y": round(point["y"], 4)})
    return out


def build_cruise_waypoints(slots: list[SlotRef]) -> list[dict]:
    """Full waypoint list including all 54 inspection checkpoints.

    Each waypoint is ``{x, y, kind, theta?, slot_code?, sequence?}`` with
    kind in {WAITING, TRANSIT, TURN, INSPECTION}. This is what the mock robot
    executes and what the map renders.
    """
    groups = ordered_groups(slots)
    waypoints: list[dict] = [
        {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"], "kind": "WAITING", "theta": REMOTE_WAITING["theta"]},
    ]

    first = inspection_pose(groups[0][0])
    waypoints.append({"x": REMOTE_WAITING["x"], "y": first["y"], "kind": "TRANSIT"})
    waypoints.append({"x": first["x"], "y": first["y"], "kind": "TRANSIT"})

    sequence = 0
    for group_index, group in enumerate(groups):
        for slot in group:
            sequence += 1
            pose = inspection_pose(slot)
            waypoints.append(
                {
                    "x": pose["x"],
                    "y": pose["y"],
                    "theta": pose["theta"],
                    "kind": "INSPECTION",
                    "slot_code": slot.code,
                    "sequence": sequence,
                }
            )
        if group_index == len(groups) - 1:
            continue
        end = inspection_pose(group[-1])
        nxt = inspection_pose(groups[group_index + 1][0])
        if group_index in (0, 2):
            # col1→col2 and col3→col4 exit at the bottom: transverse y=1.5.
            waypoints.append({"x": end["x"], "y": 1.5, "kind": "TURN"})
            waypoints.append({"x": nxt["x"], "y": 1.5, "kind": "TURN"})
        elif group_index == 1:
            # col2→col3 exit at the top: transverse y=27.0.
            waypoints.append({"x": end["x"], "y": 27.0, "kind": "TURN"})
            waypoints.append({"x": nxt["x"], "y": 27.0, "kind": "TURN"})
        else:
            # col4→top row: exit north onto the top inspection lane (A18).
            waypoints.append({"x": end["x"], "y": nxt["y"], "kind": "TURN"})

    top_end = inspection_pose(groups[-1][-1])
    waypoints.append({"x": REMOTE_WAITING["x"], "y": top_end["y"], "kind": "TRANSIT"})
    waypoints.append(
        {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"], "kind": "WAITING", "theta": REMOTE_WAITING["theta"]}
    )
    return waypoints


def build_cruise_trajectory(slots: list[SlotRef]) -> list[dict]:
    """x/y path for the map polyline (axis-aligned lanes, no duplicates)."""
    return _dedupe([{"x": w["x"], "y": w["y"]} for w in build_cruise_waypoints(slots)])
