"""Right-side-coverage S-cruise geometry for the DEMO_PARKING map.

This module is the single source of truth for the demo inspection route. Both
the fresh-database seed and the existing-dev-database sync MUST call the same
builder so the two can never drift.

The robot only detects the side to its right. Every inspection pose therefore
places the parking slot in the robot's local right half-plane:

    dot(slot_center - robot_pose, vehicle_right_vector(theta)) > 0

with vehicle_right_vector(theta) = (sin(theta), -cos(theta)).

Body frame (ROS convention):

    local +X = forward
    local +Y = left
    local -Y = right

Slot codes are generated by seed.py as:

    A-01..A-09  top group 1 (x = 2.5 + col*2.15, y = 31.5)
    A-10..A-18  top group 2 (x = 27.0 + col*2.15, y = 31.5)
    A-19..A-27  column 1   (x = 5.0,  y = 3.0 + row*2.8)
    A-28..A-36  column 2   (x = 17.0, y = 3.0 + row*2.8)
    A-37..A-45  column 3   (x = 29.0, y = 3.0 + row*2.8)
    A-46..A-54  column 4   (x = 43.0, y = 3.0 + row*2.8)
"""

from __future__ import annotations

import math
from typing import NamedTuple

REMOTE_WAITING = {"x": 1.2, "y": 1.2, "theta": math.pi / 2}

_TOP_LANE_OFFSET_Y = -2.8
_COLUMN_LANE_OFFSET = 3.0
NORTH_TRANSFER_Y = 27.0  # safe east-west transfer lane north of the top row
CLEARANCE_M = 0.3


class SlotRef(NamedTuple):
    code: str
    x: float
    y: float


def slot_number(code: str) -> int:
    return int(code.rsplit("-", 1)[-1].lstrip("0") or "0")


def group_of(code: str) -> str:
    n = slot_number(code)
    if n <= 18:
        return "top"
    if n <= 27:
        return "col1"
    if n <= 36:
        return "col2"
    if n <= 45:
        return "col3"
    return "col4"


def vehicle_right_vector(theta: float) -> tuple[float, float]:
    return (math.sin(theta), -math.cos(theta))


def slot_is_on_vehicle_right(robot: dict, slot: dict) -> bool:
    rel = (slot["x"] - robot["x"], slot["y"] - robot["y"])
    right = vehicle_right_vector(robot["theta"])
    return rel[0] * right[0] + rel[1] * right[1] > 0


def inspection_pose(slot: SlotRef) -> dict:
    """Return the robot pose from which the slot is on the robot's right side."""
    group = group_of(slot.code)
    if group == "top":
        return {"x": slot.x, "y": slot.y + _TOP_LANE_OFFSET_Y, "theta": math.pi}
    if group in {"col1", "col3"}:
        return {"x": slot.x + _COLUMN_LANE_OFFSET, "y": slot.y, "theta": -math.pi / 2}
    return {"x": slot.x - _COLUMN_LANE_OFFSET, "y": slot.y, "theta": math.pi / 2}


def ordered_groups(slots: list[SlotRef]) -> list[list[SlotRef]]:
    """S-cruise order: col1 down, col2 up, col3 down, col4 up, top west."""
    col1 = sorted((s for s in slots if group_of(s.code) == "col1"), key=lambda s: -s.y)
    col2 = sorted((s for s in slots if group_of(s.code) == "col2"), key=lambda s: s.y)
    col3 = sorted((s for s in slots if group_of(s.code) == "col3"), key=lambda s: -s.y)
    col4 = sorted((s for s in slots if group_of(s.code) == "col4"), key=lambda s: s.y)
    top = sorted((s for s in slots if group_of(s.code) == "top"), key=lambda s: -s.x)
    return [col1, col2, col3, col4, top]


def ordered_codes(slots: list[SlotRef]) -> list[str]:
    return [slot.code for group in ordered_groups(slots) for slot in group]


def _dedupe(points: list[dict]) -> list[dict]:
    out: list[dict] = []
    for point in points:
        if not out or out[-1]["x"] != point["x"] or out[-1]["y"] != point["y"]:
            out.append({"x": round(point["x"], 4), "y": round(point["y"], 4)})
    return out


def build_cruise_waypoints(slots: list[SlotRef]) -> list[dict]:
    """Full waypoint list including all 54 inspection checkpoints.

    Each waypoint is ``{x, y, kind, theta?, slot_code?, sequence?}`` with
    kind in {WAITING, TRANSIT, TURN, INSPECTION}. This is what the mock robot
    executes and what the map renders.
    """
    groups = ordered_groups(slots)
    waypoints: list[dict] = [
        {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"], "kind": "WAITING", "theta": REMOTE_WAITING["theta"]},
    ]

    first = inspection_pose(groups[0][0])
    # Enter the first column from the NORTH transfer lane, not by cutting
    # laterally through A-27: (1.2,1.2) -> (1.2,27.0) -> (8.0,27.0) -> A-27.
    waypoints.append({"x": REMOTE_WAITING["x"], "y": NORTH_TRANSFER_Y, "kind": "TRANSIT"})
    waypoints.append({"x": first["x"], "y": NORTH_TRANSFER_Y, "kind": "TRANSIT"})

    sequence = 0
    for group_index, group in enumerate(groups):
        for slot in group:
            sequence += 1
            pose = inspection_pose(slot)
            waypoints.append(
                {
                    "x": pose["x"],
                    "y": pose["y"],
                    "theta": pose["theta"],
                    "kind": "INSPECTION",
                    "slot_code": slot.code,
                    "sequence": sequence,
                }
            )
        if group_index == len(groups) - 1:
            continue
        end = inspection_pose(group[-1])
        nxt = inspection_pose(groups[group_index + 1][0])
        if group_index in (0, 2):
            # col1→col2 and col3→col4 exit at the bottom: transverse y=1.5.
            waypoints.append({"x": end["x"], "y": 1.5, "kind": "TURN"})
            waypoints.append({"x": nxt["x"], "y": 1.5, "kind": "TURN"})
        elif group_index == 1:
            # col2→col3 exit at the top: transverse along the north lane.
            waypoints.append({"x": end["x"], "y": NORTH_TRANSFER_Y, "kind": "TURN"})
            waypoints.append({"x": nxt["x"], "y": NORTH_TRANSFER_Y, "kind": "TURN"})
        else:
            # col4→top row: exit north onto the top inspection lane (A18).
            waypoints.append({"x": end["x"], "y": nxt["y"], "kind": "TURN"})

    top_end = inspection_pose(groups[-1][-1])
    waypoints.append({"x": REMOTE_WAITING["x"], "y": top_end["y"], "kind": "TRANSIT"})
    waypoints.append(
        {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"], "kind": "WAITING", "theta": REMOTE_WAITING["theta"]}
    )
    return waypoints


def build_cruise_trajectory(slots: list[SlotRef]) -> list[dict]:
    """x/y path for the map polyline (axis-aligned lanes, no duplicates)."""
    return _dedupe([{"x": w["x"], "y": w["y"]} for w in build_cruise_waypoints(slots)])


# Safe corridor graph: explicit axis-aligned lanes a robot may occupy. The
# return planner runs Dijkstra over it, so the shortest legal path is chosen
# rather than reversing the cruise or hardcoding a north/south branch.
import heapq  # noqa: E402

CORRIDOR_VERTICALS: list[tuple[float, float, float]] = [
    (1.2, 1.0, 28.7),  # west outer corridor (up to the top lane)
    (8.0, 1.0, 27.0),  # col1 inspection lane (east of column 1)
    (14.0, 1.0, 27.0),  # col2 inspection lane (west of column 2)
    (32.0, 1.0, 27.0),  # col3 inspection lane (east of column 3)
    (40.0, 1.0, 28.7),  # col4 inspection lane (west of column 4, to top lane)
]
CORRIDOR_HORIZONTALS: list[tuple[float, float, float]] = [
    (1.0, 1.2, 40.0),  # south transfer
    (27.0, 1.2, 40.0),  # north transfer
    (28.7, 1.2, 44.2),  # top inspection lane
]


def _corridor_graph() -> tuple[dict, list[tuple[float, float]], dict]:
    key_to_idx: dict = {}
    node_xy: list[tuple[float, float]] = []

    def idx(x: float, y: float) -> int:
        key = (round(x, 4), round(y, 4))
        if key not in key_to_idx:
            key_to_idx[key] = len(node_xy)
            node_xy.append(key)
        return key_to_idx[key]

    adjacency: dict[int, list[tuple[int, float]]] = {}

    def link(ia: int, ib: int, w: float) -> None:
        if w < 1e-6:
            return
        adjacency.setdefault(ia, []).append((ib, w))
        adjacency.setdefault(ib, []).append((ia, w))

    for x, ymin, ymax in CORRIDOR_VERTICALS:
        ys = sorted(
            {ymin, ymax}
            | {hy for hy, xmin, xmax in CORRIDOR_HORIZONTALS if ymin <= hy <= ymax and xmin <= x <= xmax}
        )
        for a, b in zip(ys, ys[1:]):
            link(idx(x, a), idx(x, b), b - a)
    for hy, xmin, xmax in CORRIDOR_HORIZONTALS:
        xs = sorted(
            {xmin, xmax}
            | {vx for vx, ymin, ymax in CORRIDOR_VERTICALS if ymin <= hy <= ymax and xmin <= vx <= xmax}
        )
        for a, b in zip(xs, xs[1:]):
            link(idx(a, hy), idx(b, hy), b - a)

    remote = idx(REMOTE_WAITING["x"], REMOTE_WAITING["y"])
    west_south = idx(1.2, 1.0)
    link(remote, west_south, 0.2)
    return key_to_idx, node_xy, adjacency


def _dijkstra(adjacency: dict, node_xy: list, start: int, goal: int) -> list[int] | None:
    dist = {start: 0.0}
    prev: dict[int, int] = {}
    queue = [(0.0, start)]
    while queue:
        d, u = heapq.heappop(queue)
        if d > dist.get(u, math.inf):
            continue
        if u == goal:
            break
        for v, w in adjacency.get(u, []):
            nd = d + w
            if nd < dist.get(v, math.inf):
                dist[v] = nd
                prev[v] = u
                heapq.heappush(queue, (nd, v))
    if goal not in dist:
        return None
    path = [goal]
    while path[-1] != start:
        path.append(prev[path[-1]])
    path.reverse()
    return path


def _project_onto_segments(cx: float, cy: float, segments: list[tuple[tuple[float, float], tuple[float, float]]]) -> tuple[float, tuple[float, float], int]:
    best: tuple[float, tuple[float, float], int] | None = None
    for i, ((ax, ay), (bx, by)) in enumerate(segments):
        dx, dy = bx - ax, by - ay
        length2 = dx * dx + dy * dy
        if length2 < 1e-9:
            proj = (ax, ay)
        else:
            t = ((cx - ax) * dx + (cy - ay) * dy) / length2
            t = max(0.0, min(1.0, t))
            proj = (ax + t * dx, ay + t * dy)
        d = math.hypot(cx - proj[0], cy - proj[1])
        if best is None or d < best[0]:
            best = (d, proj, i)
    assert best is not None
    return best


def _corridor_segments() -> list[tuple[tuple[float, float], tuple[float, float]]]:
    segments: list[tuple[tuple[float, float], tuple[float, float]]] = []
    for x, ymin, ymax in CORRIDOR_VERTICALS:
        segments.append(((x, ymin), (x, ymax)))
    for hy, xmin, xmax in CORRIDOR_HORIZONTALS:
        segments.append(((xmin, hy), (xmax, hy)))
    return segments


def _project_onto_route(cx: float, cy: float, waypoints: list[dict]) -> tuple[float, tuple[float, float], int, int]:
    """Return (distance, projection, seg_a_idx, seg_b_idx) of the nearest cruise segment."""
    best: tuple[float, tuple[float, float], int, int] | None = None
    for i, (a, b) in enumerate(zip(waypoints, waypoints[1:])):
        ax, ay = a["x"], a["y"]
        bx, by = b["x"], b["y"]
        dx, dy = bx - ax, by - ay
        length2 = dx * dx + dy * dy
        if length2 < 1e-9:
            proj = (ax, ay)
        else:
            t = ((cx - ax) * dx + (cy - ay) * dy) / length2
            t = max(0.0, min(1.0, t))
            proj = (ax + t * dx, ay + t * dy)
        d = math.hypot(cx - proj[0], cy - proj[1])
        if best is None or d < best[0]:
            best = (d, proj, i, i + 1)
    assert best is not None
    return best


def build_return_waypoints(current_pose: dict, full_waypoints: list[dict] | None = None, route_cursor: int | None = None) -> list[dict]:
    """Shortest safe return-to-waiting path over the corridor graph.

    Projects the current pose onto the nearest corridor lane, runs Dijkstra to
    REMOTE_WAITING, and only falls back to a simple corridor path when the
    pose is far from every known lane.
    """
    cx = float(current_pose["x"])
    cy = float(current_pose["y"])

    key_to_idx, node_xy, adjacency = _corridor_graph()
    segments = _corridor_segments()
    dist_to_lane, proj, _seg = _project_onto_segments(cx, cy, segments)
    if dist_to_lane > 2.0:
        return _fallback_return(cx, cy)

    proj_key = (round(proj[0], 4), round(proj[1], 4))
    if proj_key not in key_to_idx:
        key_to_idx[proj_key] = len(node_xy)
        node_xy.append(proj_key)
    proj_idx = key_to_idx[proj_key]
    # Connect the projection to the two ends of the lane it lies on.
    for x, ymin, ymax in CORRIDOR_VERTICALS:
        if abs(proj[0] - x) < 1e-6 and ymin <= proj[1] <= ymax:
            a = key_to_idx[(round(x, 4), round(ymin, 4))]
            b = key_to_idx[(round(x, 4), round(ymax, 4))]
            adjacency.setdefault(proj_idx, []).append((a, abs(proj[1] - ymin)))
            adjacency.setdefault(a, []).append((proj_idx, abs(proj[1] - ymin)))
            adjacency.setdefault(proj_idx, []).append((b, abs(ymax - proj[1])))
            adjacency.setdefault(b, []).append((proj_idx, abs(ymax - proj[1])))
            break
    else:
        for hy, xmin, xmax in CORRIDOR_HORIZONTALS:
            if abs(proj[1] - hy) < 1e-6 and xmin <= proj[0] <= xmax:
                a = key_to_idx[(round(xmin, 4), round(hy, 4))]
                b = key_to_idx[(round(xmax, 4), round(hy, 4))]
                adjacency.setdefault(proj_idx, []).append((a, abs(proj[0] - xmin)))
                adjacency.setdefault(a, []).append((proj_idx, abs(proj[0] - xmin)))
                adjacency.setdefault(proj_idx, []).append((b, abs(xmax - proj[0])))
                adjacency.setdefault(b, []).append((proj_idx, abs(xmax - proj[0])))
                break

    remote_key = (round(REMOTE_WAITING["x"], 4), round(REMOTE_WAITING["y"], 4))
    if remote_key not in key_to_idx:
        return _fallback_return(cx, cy)
    remote_idx = key_to_idx[remote_key]
    path = _dijkstra(adjacency, node_xy, proj_idx, remote_idx)
    if path is None:
        return _fallback_return(cx, cy)

    result: list[dict] = [{"x": cx, "y": cy, "kind": "TRANSIT"}]
    for node in path:
        x, y = node_xy[node]
        if abs(x - REMOTE_WAITING["x"]) < 1e-6 and abs(y - REMOTE_WAITING["y"]) < 1e-6:
            result.append({"x": x, "y": y, "kind": "WAITING", "theta": REMOTE_WAITING["theta"]})
        else:
            result.append({"x": x, "y": y, "kind": "TRANSIT"})
    return _dedupe_waypoints(result)


def _fallback_return(cx: float, cy: float) -> list[dict]:
    waypoints: list[dict] = [{"x": cx, "y": cy, "kind": "TRANSIT"}]
    vx = min((lane[0] for lane in CORRIDOR_VERTICALS), key=lambda x: abs(x - cx))
    if abs(vx - cx) > 1e-6:
        waypoints.append({"x": vx, "y": cy, "kind": "TRANSIT"})
    waypoints.append({"x": vx, "y": 1.0, "kind": "TRANSIT"})
    waypoints.append({"x": REMOTE_WAITING["x"], "y": 1.0, "kind": "TRANSIT"})
    waypoints.append(
        {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"], "kind": "WAITING", "theta": REMOTE_WAITING["theta"]}
    )
    return _dedupe_waypoints(waypoints)


def infer_route_cursor(current_pose: dict, full_waypoints: list[dict]) -> dict:
    """Infer the interrupted segment from the current pose.

    Returns {last_completed_waypoint_index, target_waypoint_index}. When the
    robot is between waypoint i and i+1, the cursor says "completed i, heading
    to i+1".
    """
    cx = float(current_pose["x"])
    cy = float(current_pose["y"])
    _dist, _proj, seg_a, seg_b = _project_onto_route(cx, cy, full_waypoints)
    return {"last_completed_waypoint_index": seg_a, "target_waypoint_index": seg_b}


def build_resumed_cruise_waypoints(current_pose: dict, full_waypoints: list[dict], route_cursor: int | None = None) -> list[dict]:
    """Continue a cancelled cruise from the current pose onto the target
    waypoint, then the remaining canonical waypoints. Never re-runs REMOTE."""
    if route_cursor is None:
        cursor = infer_route_cursor(current_pose, full_waypoints)
        route_cursor = cursor["target_waypoint_index"]
    target = min(route_cursor, len(full_waypoints) - 1)
    remaining = full_waypoints[target:]
    head: list[dict] = [{"x": current_pose["x"], "y": current_pose["y"], "kind": "TRANSIT"}]
    if remaining and remaining[0]["x"] == head[0]["x"] and remaining[0]["y"] == head[0]["y"]:
        return remaining
    if not remaining:
        return head + [
            {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"], "kind": "WAITING", "theta": REMOTE_WAITING["theta"]}
        ]
    return head + remaining


def _dedupe_waypoints(points: list[dict]) -> list[dict]:
    out: list[dict] = []
    for point in points:
        if not out or out[-1]["x"] != point["x"] or out[-1]["y"] != point["y"]:
            out.append(point)
    return out


def segment_intersects_slot(a: dict, b: dict, slot: SlotRef, half_width: float, half_height: float, margin: float) -> bool:
    """True if the segment a->b intersects the slot's expanded AABB."""
    min_x = slot.x - half_width - margin
    max_x = slot.x + half_width + margin
    min_y = slot.y - half_height - margin
    max_y = slot.y + half_height + margin

    # Segment vs AABB via slab test.
    def in_bounds(x: float, y: float) -> bool:
        return min_x <= x <= max_x and min_y <= y <= max_y

    if in_bounds(a["x"], a["y"]) or in_bounds(b["x"], b["y"]):
        return True

    # Check each edge for intersection with the segment.
    def crosses(p: tuple[float, float], q: tuple[float, float]) -> bool:
        d1 = _cross((a["x"], a["y"]), (b["x"], b["y"]), p)
        d2 = _cross((a["x"], a["y"]), (b["x"], b["y"]), q)
        d3 = _cross(p, q, (a["x"], a["y"]))
        d4 = _cross(p, q, (b["x"], b["y"]))
        if ((d1 > 0 and d2 < 0) or (d1 < 0 and d2 > 0)) and ((d3 > 0 and d4 < 0) or (d3 < 0 and d4 > 0)):
            return True
        return False

    corners = [(min_x, min_y), (max_x, min_y), (max_x, max_y), (min_x, max_y)]
    for index in range(4):
        if crosses(corners[index], corners[(index + 1) % 4]):
            return True
    return False


def _cross(o: tuple[float, float], a: tuple[float, float], b: tuple[float, float]) -> float:
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
