"""Right-side-coverage S-cruise geometry for the DEMO_PARKING map.

This module is the single source of truth for the demo inspection route. Both
the fresh-database seed and the existing-dev-database sync MUST call the same
builder so the two can never drift.

The robot only detects the side to its right. Every inspection pose therefore
places the parking slot in the robot's local right half-plane:

    dot(slot_center - robot_pose, vehicle_right_vector(theta)) > 0

with vehicle_right_vector(theta) = (sin(theta), -cos(theta)).

Slot codes are generated by seed.py as:

    A-01..A-09  top group 1 (x = 2.5 + col*2.15, y = 31.5, heading pi)
    A-10..A-18  top group 2 (x = 27.0 + col*2.15, y = 31.5, heading pi)
    A-19..A-27  column 1   (x = 5.0,  y = 3.0 + row*2.8, heading pi/2)
    A-28..A-36  column 2   (x = 17.0, y = 3.0 + row*2.8, heading pi/2)
    A-37..A-45  column 3   (x = 29.0, y = 3.0 + row*2.8, heading pi/2)
    A-46..A-54  column 4   (x = 43.0, y = 3.0 + row*2.8, heading pi/2)
"""

from __future__ import annotations

import math
from typing import NamedTuple

REMOTE_WAITING = {"x": 1.2, "y": 1.2, "theta": math.pi / 2}

# Lane offsets relative to a slot centre, per group.
_TOP_LANE_OFFSET_Y = -2.8
_COLUMN_LANE_OFFSET = 3.0


class SlotRef(NamedTuple):
    code: str
    x: float
    y: float


def slot_number(code: str) -> int:
    return int(code.rsplit("-", 1)[-1].lstrip("0") or "0")


def group_of(code: str) -> str:
    n = slot_number(code)
    if n <= 18:
        return "top"
    if n <= 27:
        return "col1"
    if n <= 36:
        return "col2"
    if n <= 45:
        return "col3"
    return "col4"


def vehicle_right_vector(theta: float) -> tuple[float, float]:
    return (math.sin(theta), -math.cos(theta))


def slot_is_on_vehicle_right(robot: dict, slot: dict) -> bool:
    rel = (slot["x"] - robot["x"], slot["y"] - robot["y"])
    right = vehicle_right_vector(robot["theta"])
    return rel[0] * right[0] + rel[1] * right[1] > 0


def inspection_pose(slot: SlotRef) -> dict:
    """Return the robot pose from which the slot is on the robot's right side."""
    group = group_of(slot.code)
    if group == "top":
        return {"x": slot.x, "y": slot.y + _TOP_LANE_OFFSET_Y, "theta": math.pi}
    if group in {"col1", "col3"}:
        # Robot drives south (-pi/2); the slot column lies to its right (west).
        return {"x": slot.x + _COLUMN_LANE_OFFSET, "y": slot.y, "theta": -math.pi / 2}
    # col2 / col4: robot drives north (+pi/2); the slot column lies to its right (east).
    return {"x": slot.x - _COLUMN_LANE_OFFSET, "y": slot.y, "theta": math.pi / 2}


def ordered_codes(slots: list[SlotRef]) -> list[str]:
    """S-cruise order: col1 down, col2 up, col3 down, col4 up, top west."""
    top = sorted((s for s in slots if group_of(s.code) == "top"), key=lambda s: -s.x)
    col1 = sorted((s for s in slots if group_of(s.code) == "col1"), key=lambda s: -s.y)
    col2 = sorted((s for s in slots if group_of(s.code) == "col2"), key=lambda s: s.y)
    col3 = sorted((s for s in slots if group_of(s.code) == "col3"), key=lambda s: -s.y)
    col4 = sorted((s for s in slots if group_of(s.code) == "col4"), key=lambda s: s.y)
    return [s.code for s in [*col1, *col2, *col3, *col4, *top]]


def _interpolate_lane(a: tuple[float, float], b: tuple[float, float]) -> list[dict]:
    """Forward-only 90-degree connector between two lane endpoints."""
    waypoints: list[dict] = [{"x": a[0], "y": a[1]}]
    # Turn through an intermediate corner rather than cutting diagonally.
    if abs(a[0] - b[0]) > 1e-6 and abs(a[1] - b[1]) > 1e-6:
        waypoints.append({"x": a[0], "y": b[1]})
    waypoints.append({"x": b[0], "y": b[1]})
    return waypoints


def build_cruise_trajectory(slots: list[SlotRef]) -> list[dict]:
    """Build the full S-cruise path from REMOTE_WAITING and back."""
    by_code = {s.code: s for s in slots}
    col1 = [by_code[c] for c in ordered_codes(slots) if group_of(c) == "col1"]
    col2 = [by_code[c] for c in ordered_codes(slots) if group_of(c) == "col2"]
    col3 = [by_code[c] for c in ordered_codes(slots) if group_of(c) == "col3"]
    col4 = [by_code[c] for c in ordered_codes(slots) if group_of(c) == "col4"]
    top = [by_code[c] for c in ordered_codes(slots) if group_of(c) == "top"]

    p1 = inspection_pose(col1[0])  # col1 top (A27)
    p1_end = inspection_pose(col1[-1])  # col1 bottom (A19)
    p2 = inspection_pose(col2[0])  # col2 bottom (A28)
    p2_end = inspection_pose(col2[-1])  # col2 top (A36)
    p3 = inspection_pose(col3[0])  # col3 top (A45)
    p3_end = inspection_pose(col3[-1])  # col3 bottom (A37)
    p4 = inspection_pose(col4[0])  # col4 bottom (A46)
    p4_end = inspection_pose(col4[-1])  # col4 top (A54)
    p5 = inspection_pose(top[0])  # top east (A18)
    p5_end = inspection_pose(top[-1])  # top west (A01)

    path: list[dict] = [
        {"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"]},
    ]
    # West perimeter north, then east into the col1 top lane.
    path.append({"x": 1.2, "y": p1["y"]})
    path.append({"x": p1["x"], "y": p1["y"]})
    # col1 down, bottom transverse, col2 up, top transverse, col3 down,
    # bottom transverse, col4 up, then east to the top lane.
    path.append({"x": p1_end["x"], "y": p1_end["y"]})
    path.extend(_interpolate_lane((p1_end["x"], 1.5), (p2["x"], 1.5)))
    path.append({"x": p2["x"], "y": p2["y"]})
    path.append({"x": p2_end["x"], "y": p2_end["y"]})
    path.extend(_interpolate_lane((p2_end["x"], 27.0), (p3["x"], 27.0)))
    path.append({"x": p3["x"], "y": p3["y"]})
    path.append({"x": p3_end["x"], "y": p3_end["y"]})
    path.extend(_interpolate_lane((p3_end["x"], 1.5), (p4["x"], 1.5)))
    path.append({"x": p4["x"], "y": p4["y"]})
    path.append({"x": p4_end["x"], "y": p4_end["y"]})
    path.extend(_interpolate_lane((p4_end["x"], p5["y"]), (p5["x"], p5["y"])))
    path.append({"x": p5_end["x"], "y": p5_end["y"]})
    # Leave A01, travel west then south back to the remote waiting area.
    path.append({"x": 1.2, "y": p5_end["y"]})
    path.append({"x": REMOTE_WAITING["x"], "y": REMOTE_WAITING["y"]})

    # Drop consecutive duplicate waypoints.
    deduped: list[dict] = []
    for point in path:
        if not deduped or (deduped[-1]["x"] != point["x"] or deduped[-1]["y"] != point["y"]):
            deduped.append({"x": round(point["x"], 4), "y": round(point["y"], 4)})
    return deduped
