logLevel: info
api: yes
apiAddress: :9997
authMethod: http
authHTTPAddress: http://api:8000/api/v1/media/authorize
authHTTPExclude:
  - action: api
  - action: metrics
  - action: pprof
metrics: yes
metricsAddress: :9998
rtsp: yes
rtspAddress: :8554
webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: []
paths:
  all_others:
